<?php

return [
    'cover_category' => 'uploads/cover_category/',
    'admin_category' => 4,
    'cover_category_path' => public_path() . '/uploads/cover_category/',
    'avatar_path' => public_path() . '/uploads/avatar/',
    'avatar_default' => 'default-avatar.png',
    'source_music' => 'public/uploads/music',
    'source_audio' => 'public/uploads/audio',
    'user_per_page' => 5,
    'avatar' => '/uploads/avatar/',
    'find_error' => 'Find Id Error,Please try again',
    'null' => 'N/A',
    'cover_default' => 'default_cover.jpg',
    'audio' => 'audio',
    'video' => 'video',
    'audio_per_page' => 5,
    'audio_path' => '/uploads/audio/',
    'audio_cover_path' => '/uploads/cover/audio_cover/',
    'audio_src' => public_path() . '/uploads/audio/',
    'audio_cover_src' => public_path() . '/uploads/cover/audio_cover/',
    'none' => 'None',
    'video_per_page' => 5,
    'video_path' => '/uploads/video/',
    'video_cover_path' => '/uploads/cover/video_cover/',
    'video_src' => public_path() . '/uploads/video/',
    'video_cover_src' => public_path() . '/uploads/cover/video_cover/',
];
