<?php

return [
    'cover_category_path' => 'uploads/cover/category_cover/',
    'admin_category' => 10,
    'cover_category_src' => public_path() . '/uploads/cover/category_cover/',
    'avatar_path' => public_path() . '/uploads/avatar/',
    'avatar_default' => 'default-avatar.png',
    'source_music' => 'public/uploads/music',
    'source_audio' => 'public/uploads/audio',
    'user_per_page' => 5,
    'avatar' => '/uploads/avatar/',
    'find_error' => 'Find Id Error,Please try again',
    'null' => 'N/A',
    'cover_default' => 'default_cover.jpg',
    'audio' => 'audio',
    'video' => 'video',
    'audio_per_page' => 5,
    'lyric_per_page' => 5,
    'search_lyric_per_page' => 10,
    'album_per_page' => 10,
    'search_per_page' => 10,
    'audio_path' => '/uploads/audio/',
    'audio_cover_path' => '/uploads/cover/audio_cover/',
    'audio_src' => public_path() . '/uploads/audio/',
    'audio_cover_src' => public_path() . '/uploads/cover/audio_cover/',
    'none' => 'None',
    'video_per_page' => 5,
    'singer_per_page' => 5,
    'video_path' => '/uploads/video/',
    'video_cover_path' => '/uploads/cover/video_cover/',
    'video_src' => public_path() . '/uploads/video/',
    'video_cover_src' => public_path() . '/uploads/cover/video_cover/',
    'album_cover_src' => public_path() . '/uploads/cover/album_cover/',
    'album_cover_path' => '/uploads/cover/album_cover/',
    'singer' => [
        'solo' => 'Solo',
        'duet' => 'Duet',
        'group' => 'Group',
        'other' => 'Other',
    ],
    'current-lyric' => 1,
    'not-accept-lyric' => 0,
    'admin' => 'Admin',
    'user' => 'User',
    'rate' => [
        'song' => 1,
        'album' => 2,
    ],
    'category' => [
        'song' => 'song',
        'album' => 'album',
    ],
];
